### ISSUE TITLE
How can I specify my settings.xml ?

### ISSUE THREAD

**Issue by rhuanpacto** [andreptb/Dockerfiles#27]
I'm trying to build the project but I need to connect to my Nexus URL.
The configuration inside my settings.xml, but how can I pass it as parameter?

**Comment by andrealbinop** [comment]
@rhuanpacto,

Since **settings.xml** is not provided, just like [library/maven](carlossg/docker-maven), a solution for your problem is out of scope for our base [maven](maven/README.md) image.

[library/maven suggests](https://github.com/carlossg/docker-maven#packaging-a-local-repository-with-the-image) that you create your own image setting up a local repository. This setup also carries your **settings.xml** which can already contain your Nexus URL.
